from django.conf import settings
import os

TEMP_REPO_STORAGE_LOCATION = os.path.join(settings.BASE_DIR, "temp_repo_storage")
REFACTORED_REPO_STORAGE_LOCATION = os.path.join(
    settings.BASE_DIR, "refactored_repo_storage"
)
GITHUB_URL_BITS = {
    "base": "https://github.com/",
    "zip_file_tail": "/archive/master.zip",
}

# This will change every time the backend is re-run
TEMPORARY_NGROK_URL = "https://3f09-34-145-121-27.ngrok.io"


REPO_OWNER_PARAM = "repo-owner"
REPO_NAME_PARAM = "repo-name"
ACCESS_TOKEN_PARAM = "access-token"
GENERATE_GITHUB_ISSUE_PARAM = "generate-github-issue"
LLM_ENGINE_PARAM = "llm-engine"
ORIGINAL_TEXT_PARAM = "original-text"
TERM_PARAM = "term"
LANGUAGE_PARAM = "language-mode"
CODE_STRING_PARAM = "file-content"
CODEBASE_ANALYSIS_PARAM = "codebase-analysis"
REFACTORS_PARAM = "refactors"
COMMIT_MESSAGE_PARAM = "commit-message"
UUID_PARAM = "uuid"

SSPM = "Sub-String Pattern Matching"
WBPM = "Word-Boundary Pattern Matching"

GPT4_ENGINE = "GPT-4"
LLAMA7B_ENGINE = "llama-7b"

SUPPORTED_LANGUAGES = {
    "python": ".py",
    "java": ".java",
}
LANGUAGE_ADDONS = {
    "python": ["aliases"],
    "java": [],
}
SUPPORTED_LANGUAGES_REFACTORING = {"python": ".py"}


RESPONSE_DELIMITER = "RESPONSE:"
PROMPT_TEMPLATES = {
    "non-code-inclusive": {
        "pre-term": "Below is an instruction that describes a task. Write a response that appropriately completes the request.\n INSTRUCTION: Make the following text more inclusive by avoiding the use of these words: ",
        "pre-text": "TEXT: ",
        "post-text": RESPONSE_DELIMITER,
    }
}

INCLUSIFIER_COMMENT_WATERMARK = (
    "\n*This issue comment has been generated by Inclusifier.*"
)
INCLUSIFIER_PR_WATERMARK = "\n\n*This pull request has been generated by Inclusifier.*"
ISSUE_TITLE = "Non-inclusive Language Report"
ISSUE_BODY = f"In the thread below, a summary of the non-inclusive language found in this repository has been generated, **grouped by non-inclusive language category.**{INCLUSIFIER_COMMENT_WATERMARK}"


PDF = "pdf"
DEFAULT_UNREADABLE_FILE_TYPES = [
    #    image formats
    "apng",
    "avif",
    "bmp",
    "bpg",
    "cdr",
    "cmx",
    "cpt",
    "cr2",
    "djvu",
    "dxf",
    "emf",
    "eps",
    "gif",
    "heif",
    "ico",
    "indd",
    "jp2",
    "jpeg",
    "jpg",
    "jxr",
    "kra",
    "mng",
    "nef",
    "ora",
    "pict",
    "png",
    "ps",
    "psd",
    "raw",
    "svg",
    "tga",
    "tif",
    "tiff",
    "webp",
    "wmf",
    "xcf",
    #  misc
]

FAILED_FILE_READ_WARNING = (
    "WARNING: File type not currently supported - contents no analysed."
)

NON_INCLUSIVE_LANGUAGE_TERMS = {
    "ABLEIST LANGUAGE": [
        "crazy",
        "sane",
        "insane",
        "blind",
        "cripple",
        "dumb",
        "sanity-check",
        "sanity check",
        "dummy",
        "bonkers",
        "mad",
        "lunatic",
        "loony",
        "deficient",
        "deformed",
        "dumb",
        "gimp",
        "retarded",
        "unsighted",
        "visually challenged",
    ],
    "GENDERED LANGUAGE": [
        "man-hours",
        "man hours",
        "manhours",
        "manking",
        "male adapter",
        "female adapter",
        "guys",
        "manned",
        "man made",
        "manmade",
        "manpower",
        "man power",
        "man-power",
        "mom test",
        "grandmother test",
        "girlfriend test",
        "chairman",
        "mans",
        "salesman",
        "daughter board",
        "female connector",
        "male connector",
        "gender bender",
    ],
    "VIOLENT LANGUAGE": [
        "stonith",
        "hang",
        "hung",
        "hit",
        "abort",
        "blast radius",
        "kill",
        "nuke",
        "terminate",
    ],
    "AGEIST LANGUAGE": ["the elderly", "the aged", "seniors", "senior citizen"],
    "RACIALLY CHARGED LANGUAGE": [
        "whitelist",
        "white list",
        "white-list",
        "blacklist",
        "black list",
        "black-list",
        "native",
        "first-class citizen",
        "first class citizen",
        "master",
        "slave",
        "blackbox",
        "black box",
        "black-box",
        "whitebox",
        "white box",
        "white-box",
        "blackhole",
        "blackhat",
        "black hat",
        "black-hat",
        "whitehat",
        "white hat",
        "white-hat",
        "first-class",
        "first class",
        "ghetto",
        "gypsy",
        "primitive",
        "tribal knowledge",
        "tribal wisdom",
        "webmaster",
        "web master",
        "web-master",
        "whiteglove",
        "white glove",
        "white-glove",
        "whitelabel",
        "white label",
        "white-label",
        "quantum supremacy",
    ],
    "BIASED LANGUAGE": [
        "normal",
        "healthy",
        "health check",
        "abnormal",
        "sick",
        "disabled",
        "quadriplegic",
        "victim of",
        "suffering from",
        "wheelchair-bound",
        "physically challenged",
        "special",
        "differently abled",
        "handi-capable",
        "handicapped",
        "average user",
    ],
    "MILITARY LANGUAGE": [
        "demilitarized zone",
        "outpost",
        "war room",
        "warroom",
        "war-room",
    ],
    "OTHER": [
        "chubby",
        "denigrate",
        "fat",
        "hands on",
        "hands-on",
        "hands off",
        "hands-off",
        "jank",
        "lame",
        "monkey test",
        "ninja",
        "sexy",
        "orphaned object",
    ],
}
